<?php

namespace App\Exports;

use App\Models\Receipt;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Font;
use PhpOffice\PhpSpreadsheet\Style\PatternFill;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Protection;

class GeneratedReceiptExport implements FromCollection, WithHeadings, WithStyles
{
    private $receipts;

    public function __construct($receipts)
    {
        $this->receipts = $receipts;
    }

    public function collection()
    {
        return $this->receipts->map(fn ($receipt) => [
            'Receipt Number' => $receipt->receipt_number,
            'Type' => $receipt->consignment_nature,
            'Route' => $receipt->route?->name ?? 'N/A',
            'Long Route' => $receipt->longRoute?->name ?? 'N/A',
            'Trucks' => $receipt->moving_trucks,
            'Total (GMD)' => number_format($receipt->total_charge_gmd, 2),
            'Usage' => $receipt->used > 0 ? "Available ({$receipt->used} remaining)" : 'Fully Used',
            'Generated By' => $receipt->generatedByUser?->name ?? 'System',
            'Created Date' => $receipt->created_at?->format('Y-m-d H:i') ?? 'N/A',
            'SAD Number' => $receipt->sad_number,
            'Destination' => $receipt->destination?->name ?? 'N/A',
        ]);
    }

    public function headings(): array
    {
        return [
            'Receipt Number',
            'Type',
            'Route',
            'Long Route',
            'Trucks',
            'Total (GMD)',
            'Usage',
            'Generated By',
            'Created Date',
            'SAD Number',
            'Destination',
        ];
    }

    public function styles(Worksheet $sheet)
    {
        $headerStyle = [
            'font' => [
                'bold' => true,
                'color' => ['rgb' => 'FFFFFF'],
                'size' => 12,
            ],
            'fill' => [
                'fillType' => PatternFill::FILL_SOLID,
                'startColor' => ['rgb' => '1E40AF'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['rgb' => '000000'],
                ],
            ],
        ];

        // Apply header styling
        $sheet->getStyle('A1:K1')->applyFromArray($headerStyle);

        // Apply data styling
        $dataStyle = [
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_LEFT,
                'vertical' => Alignment::VERTICAL_CENTER,
                'wrapText' => true,
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['rgb' => 'D3D3D3'],
                ],
            ],
        ];

        $sheet->getStyle('A2:K' . $sheet->getHighestRow())->applyFromArray($dataStyle);

        // Set column widths
        $sheet->getColumnDimension('A')->setWidth(20);
        $sheet->getColumnDimension('B')->setWidth(12);
        $sheet->getColumnDimension('C')->setWidth(18);
        $sheet->getColumnDimension('D')->setWidth(18);
        $sheet->getColumnDimension('E')->setWidth(10);
        $sheet->getColumnDimension('F')->setWidth(15);
        $sheet->getColumnDimension('G')->setWidth(20);
        $sheet->getColumnDimension('H')->setWidth(20);
        $sheet->getColumnDimension('I')->setWidth(20);
        $sheet->getColumnDimension('J')->setWidth(20);
        $sheet->getColumnDimension('K')->setWidth(20);

        // Freeze header row
        $sheet->freezePane('A2');

        return [];
    }
}
