<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Font;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use Illuminate\Support\Collection;

class GeneratedReceiptsExport implements FromCollection, WithHeadings, WithStyles, WithEvents
{
    protected Collection $receipts;
    protected ?array $statistics = null;

    public function __construct(Collection $receipts, ?array $statistics = null)
    {
        $this->receipts = $receipts;
        $this->statistics = $statistics;
    }

    /**
     * Get the collection for the export
     */
    public function collection()
    {
        $data = collect();
        
        // Add statistics section if available
        if ($this->statistics) {
            $data->push(['STATISTICS SUMMARY']);
            $data->push(['']);
            $data->push(['Total Receipts:', $this->statistics['total_receipts'] ?? 0]);
            $data->push(['Total Trucks:', $this->statistics['total_trucks'] ?? 0]);
            $data->push(['Total Amount (GMD):', $this->statistics['total_amount'] ?? 0]);
            $data->push(['Total Short Routes:', $this->statistics['total_short_routes'] ?? 0]);
            $data->push(['Total Long Routes:', $this->statistics['total_long_routes'] ?? 0]);
            $data->push(['']);
            $data->push(['RECEIPTS DETAIL']);
            $data->push(['']);
        }
        
        // Add receipt data
        $receiptData = $this->receipts->map(function ($receipt) {
            return [
                $receipt->receipt_number,
                $receipt->sad_number,
                $receipt->route?->name ?? 'N/A',
                $receipt->longRoute?->name ?? 'N/A',
                $receipt->allocationPoint?->name ?? 'N/A',
                $receipt->destination?->name ?? 'N/A',
                $receipt->created_at?->format('Y-m-d H:i') ?? 'N/A',
                $receipt->moving_trucks,
                $receipt->used,
                $receipt->total_charge_gmd,
                $receipt->generatedByUser?->name ?? 'N/A',
            ];
        });
        
        return $data->concat($receiptData);
    }

    /**
     * Define the headings for the export
     */
    public function headings(): array
    {
        return [
            'Receipt Number',
            'SAD/T1',
            'Route (Short)',
            'Route (Long)',
            'Allocation Point',
            'Destination',
            'Date & Time',
            'Trucks',
            'Available Usage',
            'Total Charged (GMD)',
            'Generated By',
        ];
    }

    /**
     * Register events for styling
     */
    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $sheet = $event->sheet;

                // Style header row
                $headerStyle = [
                    'font' => [
                        'bold' => true,
                        'color' => ['rgb' => 'FFFFFF'],
                        'size' => 12,
                    ],
                    'fill' => [
                        'fillType' => Fill::FILL_SOLID,
                        'startColor' => ['rgb' => '3B82F6'], // Blue
                    ],
                    'alignment' => [
                        'horizontal' => Alignment::HORIZONTAL_CENTER,
                        'vertical' => Alignment::VERTICAL_CENTER,
                    ],
                    'borders' => [
                        'allBorders' => [
                            'borderStyle' => Border::BORDER_THIN,
                            'color' => ['rgb' => 'D1D5DB'],
                        ],
                    ],
                ];

                $sheet->getStyle('A1:J1')->applyFromArray($headerStyle);

                // Auto-size columns
                $sheet->getColumnDimension('A')->setWidth(18); // Receipt Number
                $sheet->getColumnDimension('B')->setWidth(15); // SAD/T1
                $sheet->getColumnDimension('C')->setWidth(18); // Route Short
                $sheet->getColumnDimension('D')->setWidth(18); // Route Long
                $sheet->getColumnDimension('E')->setWidth(20); // Destination
                $sheet->getColumnDimension('F')->setWidth(18); // Date & Time
                $sheet->getColumnDimension('G')->setWidth(10); // Trucks
                $sheet->getColumnDimension('H')->setWidth(16); // Available Usage
                $sheet->getColumnDimension('I')->setWidth(18); // Total Charged
                $sheet->getColumnDimension('J')->setWidth(18); // Generated By

                // Get the last row with data
                $lastRow = $sheet->getHighestRow();

                // Style data rows - alternate colors
                for ($row = 2; $row <= $lastRow; $row++) {
                    $backgroundColor = ($row % 2 === 0) ? 'F9FAFB' : 'FFFFFF';

                    $sheet->getStyle("A{$row}:J{$row}")->applyFromArray([
                        'fill' => [
                            'fillType' => Fill::FILL_SOLID,
                            'startColor' => ['rgb' => $backgroundColor],
                        ],
                        'borders' => [
                            'allBorders' => [
                                'borderStyle' => Border::BORDER_THIN,
                                'color' => ['rgb' => 'D1D5DB'],
                            ],
                        ],
                        'alignment' => [
                            'vertical' => Alignment::VERTICAL_CENTER,
                            'wrapText' => true,
                        ],
                    ]);

                    // Right align numeric columns
                    $sheet->getStyle("G{$row}:I{$row}")->getAlignment()
                        ->setHorizontal(Alignment::HORIZONTAL_RIGHT);
                }

                // Add statistics section
                $statsRow = $lastRow + 3;

                $sheet->setCellValue("A{$statsRow}", 'SUMMARY STATISTICS');
                $sheet->getStyle("A{$statsRow}")->applyFromArray([
                    'font' => ['bold' => true, 'size' => 12, 'color' => ['rgb' => '1F2937']],
                ]);

                $statsRow++;

                // Total Receipts
                $totalReceipts = $this->receipts->count();
                $sheet->setCellValue("A{$statsRow}", 'Total Receipts:');
                $sheet->setCellValue("B{$statsRow}", $totalReceipts);
                $this->styleStat($sheet, $statsRow, '3B82F6');

                $statsRow++;

                // Total Trucks
                $totalTrucks = $this->receipts->sum('moving_trucks');
                $sheet->setCellValue("A{$statsRow}", 'Total Trucks:');
                $sheet->setCellValue("B{$statsRow}", $totalTrucks);
                $this->styleStat($sheet, $statsRow, 'A855F7');

                $statsRow++;

                // Total Amount
                $totalAmount = $this->receipts->sum('total_charge_gmd');
                $sheet->setCellValue("A{$statsRow}", 'Total Amount (GMD):');
                $sheet->setCellValue("B{$statsRow}", $totalAmount);
                $sheet->getStyle("B{$statsRow}")->getNumberFormat()
                    ->setFormatCode(NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED2);
                $this->styleStat($sheet, $statsRow, '16A34A');

                $statsRow++;

                // Export timestamp
                $sheet->setCellValue("A{$statsRow}", 'Exported on:');
                $sheet->setCellValue("B{$statsRow}", now()->format('Y-m-d H:i:s'));
                $sheet->getStyle("A{$statsRow}:B{$statsRow}")->applyFromArray([
                    'font' => ['italic' => true, 'size' => 10, 'color' => ['rgb' => '6B7280']],
                ]);

                // Freeze the header row
                $sheet->freezePane('A2');
            },
        ];
    }

    /**
     * Style individual statistic row
     */
    private function styleStat($sheet, $row, $colorHex)
    {
        $sheet->getStyle("A{$row}:B{$row}")->applyFromArray([
            'font' => ['bold' => true, 'size' => 11],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['rgb' => str_replace('#', '', $colorHex) . '22'], // 22 = 10% opacity
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['rgb' => 'D1D5DB'],
                ],
            ],
        ]);

        $sheet->getStyle("B{$row}")->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_RIGHT);
    }

    /**
     * Apply styles to the sheet
     */
    public function styles($sheet)
    {
        // This is handled in registerEvents
        return [];
    }
}
