<table>
    <thead>
        <tr>
            <th colspan="2" style="background-color: #4B5563; color: white; font-weight: bold; padding: 10px; font-size: 14px;">OVERSTAY RECEIPTS REPORT - SUMMARY</th>
        </tr>
    </thead>
    <tbody>
        <tr style="height: 25px;">
            <td colspan="2"></td>
        </tr>
        <tr style="background-color: #E8F0F7;">
            <td style="border: 1px solid #ddd; padding: 10px; font-weight: bold; background-color: #2B5A7D; color: white;">REPORT PERIOD</td>
            <td style="border: 1px solid #ddd; padding: 10px;"></td>
        </tr>
        <tr>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: 600;">From Date:</td>
            <td style="border: 1px solid #ddd; padding: 8px;">{{ $statistics['start_date'] ?? 'All Records' }}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: 600;">To Date:</td>
            <td style="border: 1px solid #ddd; padding: 8px;">{{ $statistics['end_date'] ?? 'All Records' }}</td>
        </tr>
        <tr style="height: 25px;">
            <td colspan="2"></td>
        </tr>
        <tr style="background-color: #E8F0F7;">
            <td style="border: 1px solid #ddd; padding: 10px; font-weight: bold; background-color: #2B5A7D; color: white;">STATISTICS</td>
            <td style="border: 1px solid #ddd; padding: 10px;"></td>
        </tr>
        <tr>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: 600;">Total Transactions:</td>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: bold; font-size: 14px;">{{ $statistics['total_invoices'] ?? 0 }}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: 600;">Total Trucks:</td>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: bold; font-size: 14px;">{{ $statistics['total_trucks'] ?? 0 }}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: 600;">Total Amount Generated (D):</td>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: bold; font-size: 14px;">{{ number_format($statistics['total_amount'] ?? 0, 2) }}</td>
        </tr>
        <tr style="height: 25px;">
            <td colspan="2"></td>
        </tr>
        <tr style="background-color: #E8F0F7;">
            <td style="border: 1px solid #ddd; padding: 10px; font-weight: bold; background-color: #2B5A7D; color: white;">GENERATION INFO</td>
            <td style="border: 1px solid #ddd; padding: 10px;"></td>
        </tr>
        <tr>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: 600;">Generated By:</td>
            <td style="border: 1px solid #ddd; padding: 8px;">{{ $statistics['generated_by'] ?? 'System' }}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #ddd; padding: 8px; font-weight: 600;">Generated Date/Time:</td>
            <td style="border: 1px solid #ddd; padding: 8px;">{{ $statistics['generated_at']->format('Y-m-d H:i:s') ?? 'N/A' }}</td>
        </tr>
        <tr style="height: 25px;">
            <td colspan="2"></td>
        </tr>
        <tr>
            <td colspan="2" style="padding: 10px; font-size: 12px; color: #666; font-style: italic;">
                This report contains summary statistics for the filtered overstay receipts. 
                Refer to the "Overstay Receipts" sheet for detailed transaction data.
            </td>
        </tr>
    </tbody>
</table>
